---
##
# Configuration of docker compose.
# Link and run related images.
#

version: '2'

services:
  #- Infrastructure :: Support servers -#
  #- Configuration -#
  config:
    image: coffeine/config
    build:
      context: ../Config
    environment:
      VCAP_APPLICATION_PORT: 8888
    ports:
      - "8888:8888"
    links:
      - discovery
      - rabbitmq

  #- Discovery -#
  discovery:
    image: coffeine/discovery
    build:
      context: ../Discovery
    environment:
      VCAP_APPLICATION_PORT: 8761
    ports:
      - "8761:8761"
    links:
      - rabbitmq

  #- Authorisation -#
  auth:
    image: coffeine/auth
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      DB_HOST: postgres
      JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n"
    volumes:
      - .:/opt/auth
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - config
      - discovery
      - postgres
      - rabbitmq

  #- Database -#
  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: "virtuoso"
      POSTGRES_USER: "virtuoso"
      POSTGRES_PASSWORD: "virtuoso"
      PGDATA: "/var/lib/postgresql/data"

  #- JMS :: RabitMQ -#
  rabbitmq:
    image: rabbitmq:3.6
    environment:
      RABBITMQ_DEFAULT_USER: virtuoso
      RABBITMQ_DEFAULT_PASS: virtuoso
    ports:
      - "5672"

volumes:
  #- PostgreSQL -#
  postgres:
